import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { colors, fontSize, radius, spacing } from '@/theme/theme';

import type { OutreachEvent } from './events';
import { TONES, type ToneId } from './tone';
import type { MessageMode } from './types';

/**
 * "What does it say?" — tone, guidance, and a worked preview.
 *
 * The owner never writes the message for an event campaign. They choose a voice and, if
 * they want, a steer; the assistant writes each send from the real event. The preview
 * exists so that choice is not blind.
 */

type Props = {
  mode: MessageMode;
  onModeChange: (mode: MessageMode) => void;
  tone: ToneId;
  onToneChange: (tone: ToneId) => void;
  guidance: string;
  onGuidanceChange: (guidance: string) => void;
  customMessage: string;
  onCustomMessageChange: (message: string) => void;
  /** Rendered preview, already generated by the caller. */
  preview: string;
  /** The event being previewed, if any. Drives the "sample details" caption. */
  event?: OutreachEvent;
  guidancePlaceholder: string;
};

export function MessageSection({
  mode,
  onModeChange,
  tone,
  onToneChange,
  guidance,
  onGuidanceChange,
  customMessage,
  onCustomMessageChange,
  preview,
  event,
  guidancePlaceholder,
}: Props) {
  const generated = mode === 'generated';

  return (
    <View>
      <View style={styles.modeRow}>
        <ModeTab
          label="Catch writes it"
          selected={generated}
          onPress={() => onModeChange('generated')}
          testID="mode-generated"
        />
        <ModeTab
          label="Write it myself"
          selected={!generated}
          onPress={() => onModeChange('custom')}
          testID="mode-custom"
        />
      </View>

      {generated ? (
        <>
          <Text style={styles.label}>Tone</Text>
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={styles.tones}
          >
            {TONES.map((option) => {
              const selected = option.id === tone;
              return (
                <Pressable
                  key={option.id}
                  onPress={() => onToneChange(option.id)}
                  accessibilityRole="button"
                  accessibilityState={{ selected }}
                  accessibilityLabel={`${option.label}. ${option.description}`}
                  testID={`tone-${option.id}`}
                  style={[styles.tone, selected && styles.toneSelected]}
                >
                  <Text style={styles.toneIcon}>{option.icon}</Text>
                  <Text style={[styles.toneLabel, selected && styles.toneLabelSelected]}>
                    {option.label}
                  </Text>
                </Pressable>
              );
            })}
          </ScrollView>

          <Text style={styles.toneDesc}>
            {TONES.find((t) => t.id === tone)?.description}
          </Text>

          <Text style={[styles.label, styles.labelSpaced]}>Anything to add? (optional)</Text>
          <View style={styles.inputWrap}>
            <TextInput
              value={guidance}
              onChangeText={onGuidanceChange}
              placeholder={guidancePlaceholder}
              placeholderTextColor={colors.textMuted}
              style={styles.guidanceInput}
              multiline
              accessibilityLabel="Extra guidance for the assistant"
              testID="outreach-guidance"
            />
          </View>

          <Text style={[styles.label, styles.labelSpaced]}>What it will look like</Text>
          <View style={styles.previewCard}>
            <Text style={styles.previewText}>{preview}</Text>
          </View>

          {/* The honest caveat. An owner who thinks this exact text is going out will
              be surprised by the real send, and it will be their customers who see it. */}
          <Text style={styles.previewNote}>
            {event
              ? `Example only. Catch writes a fresh message each time this fires — “${event.sampleDetail}” is replaced with the real details.`
              : 'Example only. Catch writes a fresh message each time this runs.'}
          </Text>
        </>
      ) : (
        <>
          <View style={styles.inputWrap}>
            <TextInput
              value={customMessage}
              onChangeText={onCustomMessageChange}
              placeholder="Order NOW for 50% off — this hour only."
              placeholderTextColor={colors.textMuted}
              style={styles.customInput}
              multiline
              textAlignVertical="top"
              accessibilityLabel="Message"
              testID="outreach-message"
            />
          </View>
          <Text style={styles.previewNote}>
            Sent word for word, exactly as written. Nothing is generated.
          </Text>
        </>
      )}
    </View>
  );
}

function ModeTab({
  label,
  selected,
  onPress,
  testID,
}: {
  label: string;
  selected: boolean;
  onPress: () => void;
  testID: string;
}) {
  return (
    <Pressable
      onPress={onPress}
      accessibilityRole="button"
      accessibilityState={{ selected }}
      testID={testID}
      style={[styles.modeTab, selected && styles.modeTabSelected]}
    >
      <Text style={[styles.modeText, selected && styles.modeTextSelected]}>{label}</Text>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  modeRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    padding: 4,
    marginBottom: spacing.lg,
  },
  modeTab: { flex: 1, alignItems: 'center', paddingVertical: spacing.md, borderRadius: radius.sm },
  modeTabSelected: { backgroundColor: colors.surface },
  modeText: { fontSize: fontSize.sm, fontWeight: '700', color: colors.textMuted },
  modeTextSelected: { color: colors.text },

  label: { fontSize: fontSize.xs, fontWeight: '700', color: colors.textMuted, marginBottom: spacing.sm },
  labelSpaced: { marginTop: spacing.lg },

  tones: { gap: spacing.sm, paddingRight: spacing.sm },
  tone: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingVertical: 8,
    paddingHorizontal: spacing.md,
  },
  toneSelected: { backgroundColor: colors.ink, borderColor: colors.ink },
  toneIcon: { fontSize: fontSize.sm },
  toneLabel: { fontSize: fontSize.xs, fontWeight: '700', color: colors.textMuted },
  toneLabelSelected: { color: colors.textInverse },
  toneDesc: { marginTop: spacing.sm, fontSize: fontSize.xs, color: colors.textMuted },

  inputWrap: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  guidanceInput: { minHeight: 44, fontSize: fontSize.sm, lineHeight: 20, color: colors.text },
  customInput: { minHeight: 110, fontSize: fontSize.sm, lineHeight: 21, color: colors.text },

  previewCard: {
    backgroundColor: colors.ink,
    borderRadius: radius.lg,
    padding: spacing.lg,
  },
  previewText: { fontSize: fontSize.sm, lineHeight: 21, color: colors.textInverse },
  previewNote: { marginTop: spacing.sm, fontSize: fontSize.xs, lineHeight: 17, color: colors.textMuted },
});
